version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: laravel_backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html/laravel-react-app/backend
    networks:
      - app_network
    depends_on:
      - db  # Đảm bảo rằng backend chỉ khởi động khi MySQL đã sẵn sàng
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_react_db
      - DB_USERNAME=root
      - DB_PASSWORD=root

  frontend:
    build:
      context: ./frontend
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/var/www/html/laravel-react-app/frontend
    environment:
      - HOST=fe.local  # Thêm HOST để React sử dụng tên miền này
    extra_hosts:
      - "fe.local:127.0.0.1"  # Thêm dòng này
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel_react_db          # Tên database ban đầu
    volumes:
      - mysql_data:/var/lib/mysql  # Lưu trữ dữ liệu MySQL trên máy chủ
    ports:
      - "3307:3306"
    networks:
      - app_network
volumes:
  mysql_data:
    driver: local
networks:
  app_network:
    driver: bridge
